In [ ]:
import numpy  

In [ ]:
numpy.__version__

'1.19.5'

In [ ]:
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
for i in [2, 4, 6]:
  print(np.array(range(i, i+3)))

[2 3 4]
[4 5 6]
[6 7 8]


In [ ]:
np.array([range(i, i+2) for i in [2,4,6]])

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
myArray=np.full((3,5), 3.14)
type(myArray)

numpy.ndarray

In [ ]:
type(myArray[2,2])

numpy.float64

In [ ]:
np.arange(0, 20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
#create array of five between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#create 3x3 array uniformely bet 10 and 
np.random.random((3,3))

array([[0.6373189 , 0.27784797, 0.01610129],
       [0.22468447, 0.11543831, 0.65265113],
       [0.58106669, 0.10973753, 0.25462002]])

In [ ]:
np.random.normal(0,1,(3,3))

array([[ 0.46797907, -0.4114054 , -0.8252037 ],
       [-0.92437225, -0.90205913, -0.428926  ],
       [ 1.82473565,  0.3252211 ,  0.2006039 ]])

<function numpy.empty>

In [ ]:
#ran integers
#np.random.randint(0,10(3,3))

In [ ]:
np?

In [ ]:
L = list(range(10))

In [ ]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(L[0])

int

In [ ]:
str(L[5])

'5'

In [ ]:
for c in L:
    print(c)

0
1
2
3
4
5
6
7
8
9


In [ ]:
L2 = [str(c) for c in L]

In [ ]:
type(L2[2])

str

In [ ]:
LX2=[]
for c in L:
    LX2.append(str(c))
print(LX2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [ ]:
LX2=[]
for c in L:
    LX2.append(str(c))
print(LX2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [ ]:
L3 = [True, "2", 3.0, 4]

In [ ]:
[type(item) for item in L3]

[bool, str, float, int]

In [ ]:
for item in L3:
  print(type(item))

<class 'bool'>
<class 'str'>
<class 'float'>
<class 'int'>


In [ ]:
LX3 = []
for item in L3:
  LX3.append(type(item))
print(LX3)

[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]


In [ ]:
import array
L=list(range(10))
A=array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

import numpy as np2
np.random.seed(0)
x1=np2.random.randint(10, size=6)
x2=np2.random.randint(10, size=(3,4))
x3=np2.random.randint(10, size=(3,4,5))

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [ ]:
print("dtype", x3.dtype)

dtype int64


In [ ]:
print("itemSize", x3.itemsize, "bytes")

itemSize 8 bytes


In [ ]:
print("nbytes", x3.nbytes, "nbytes")

nbytes 480 nbytes


In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

5

In [ ]:
x1[4]

7

In [ ]:
x1[-1]

9

In [ ]:
x2[2, -1]

7

In [ ]:
x2[0,0]

3

In [ ]:
x2[2,-2]

7

In [ ]:
x2[2,0]

1

In [ ]:
x2[1,1]

6

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0,0]

3

In [ ]:
x2[0,0] = 12

In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]=3.14159

In [ ]:
x1

array([3, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

3

In [ ]:
for x in range(10):
  print(x)

0
1
2
3
4
5
6
7
8
9


In [ ]:
x

9

In [ ]:
x

9

In [ ]:
x=list(range(10))

In [ ]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
x[5::-2]

[5, 3, 1]

In [ ]:
x[:5]

[0, 1, 2, 3, 4]

In [ ]:
x[5:]

[5, 6, 7, 8, 9]

In [ ]:
x[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2[:2,:3]

array([[12,  5,  2,  4]])

In [ ]:
#all rows every other column
print(x2[:3, ::2])

[[12  2]
 [ 7  8]
 [ 1  7]]


In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
print(x2[:3, ::2])

[[12  2]
 [ 7  8]
 [ 1  7]]


In [ ]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
x2_sub=x2[:2,:2]

In [ ]:
x2_sub

array([[12,  5],
       [ 7,  6]])

In [ ]:
 #modify sub array

In [ ]:
x2_sub=x2[0,0]=99

In [ ]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2_sub_copy=x2[:2,:2].copy()

In [ ]:
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [ ]:
grid = np.arange(1,10)

In [ ]:
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
grid = np.arange(1,10).reshape(3,3)

In [ ]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x=np.array([1,2,3])

In [ ]:
x

array([1, 2, 3])

In [ ]:
x.reshape((1,3))

array([[1, 2, 3]])

In [ ]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [ ]:
#via newaxi

In [ ]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [ ]:
#concatinate array
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
#more than 2 arrays

In [ ]:
z=[99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [ ]:
# 2 dimensional arrays

In [ ]:
grid=np.array([[1,2,3],[4,5,6]])

In [ ]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#concat along the first axis
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#concat along the first axis another method

In [ ]:
np.concatenate([grid,grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
#concat along the 2nd axix zero indexed method
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
#working with arrays of mixed dimensions
x=np.array([1,2,3])
grid=np.array([[9,8,7],
              [6,5,4]])
#vertically stack arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
#==============================================================================================================
#Continuation of Lab -----------------------------------------------------------------------------------------

In [ ]:
#Splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
 upper, lower = np.vsplit(grid, [2])
 print(upper)
 print(lower)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)


[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
import numpy as np
np.random.seed(0)

In [ ]:
def compute_reciprocals(values):
  output = np.empty(len(values))
  for i in range(len(values)):
    output[i] = 1.0 / values[i]
  return output

In [ ]:
#The Slowness of Loops

In [ ]:
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [ ]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)


1 loop, best of 5: 2.32 s per loop


In [ ]:
#Introducing UFuncs

In [ ]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [ ]:
%timeit (1.0 / big_array)


1000 loops, best of 5: 1.71 ms per loop


In [ ]:
 np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [ ]:
 x = np.arange(9).reshape((3, 3))
 2 ** x


array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [ ]:
#Exploring NumPy’s UFuncs
#Array arithmetic

In [ ]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [ ]:
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [ ]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [ ]:
np.add(x, 2)

array([2, 3, 4, 5])

In [ ]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [ ]:
np.absolute(x)


array([2, 1, 0, 1, 2])

In [ ]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [ ]:
#Absolute value


In [ ]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [ ]:
theta = np.linspace(0, np.pi, 3)


In [ ]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [ ]:
#Exponents and logarithms

In [ ]:
 x = [1, 2, 3]
 print("x =", x)
 print("e^x =", np.exp(x))
 print("2^x =", np.exp2(x))
 print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [ ]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [ ]:
#Specialized ufuncs


In [ ]:
from scipy import special


In [ ]:
x = [1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2) =", special.beta(x, 2))


gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2) = [0.5        0.03333333 0.00909091]


In [ ]:
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))


erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [ ]:
#Advanced Ufunc Features

In [ ]:
 x = np.arange(5)
 y = np.empty(5)
 np.multiply(x, 10, out=y)
 print(y)

[ 0. 10. 20. 30. 40.]


In [ ]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)


[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [ ]:
#Aggregates


In [ ]:
x = np.arange(1, 6)
np.add.reduce(x)


15

In [ ]:
np.multiply.reduce(x)


120

In [ ]:
np.add.accumulate(x)


array([ 1,  3,  6, 10, 15])

In [ ]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [ ]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [ ]:
print(x)

[1 2 3 4 5]


In [ ]:
x*x

array([ 1,  4,  9, 16, 25])

In [ ]:
x=x.reshape(1, 5)

In [ ]:
x

array([[1, 2, 3, 4, 5]])

In [ ]:
(x+1)*x

array([[ 2,  6, 12, 20, 30]])

In [ ]:
y = x.reshape(5,1)

In [ ]:
y

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
x*y

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [ ]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [ ]:
import numpy as np
L=np.random.random(100)
sum(L)

50.461758453195614

In [ ]:
np.sum(L)

50.46175845319564

In [ ]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 5: 162 ms per loop
1000 loops, best of 5: 347 µs per loop


In [ ]:
big_array=np.random.rand(1000000)

print("Python Sum")

%timeit sum(big_array)

print("NumPy Sum")

%timeit np.sum(big_array)

Python Sum
10 loops, best of 5: 164 ms per loop
NumPy Sum
The slowest run took 5.02 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 356 µs per loop


In [ ]:
#numpy aggregates shortcut


In [ ]:
print(big_array.min(), big_array.max(), big_array.sum())

2.067514368597756e-07 0.999997425247757 499824.08189940057


In [ ]:
%timeit big_array.min()

1000 loops, best of 5: 427 µs per loop


In [ ]:
#Multidimensional aggregates
#Page 60
M=np.random.random((3,4))
print(M)

[[0.67116226 0.62982469 0.91426129 0.68221357]
 [0.85605843 0.17886    0.92158932 0.58354976]
 [0.4787359  0.86982432 0.3930739  0.09027883]]


In [ ]:
#By default, each numpy aggregtion will return the aggregate over the entire array:

In [ ]:
M.sum()

7.269432268583035

In [ ]:
#AFinding the minimum value within each column by specifying axis=0:\
M.max()

0.9215893241315334

In [ ]:
#Find the maximum value within each row by specifying axois =1

In [ ]:
M.max(axis=1)

array([0.91426129, 0.92158932, 0.86982432])

In [ ]:
x = np.array([[1,1], [1, np.nan]])

In [ ]:
np.sum(x)

nan

In [ ]:
x = np.array([[1,1], [1, np.nan]])
np.nansum(x)

3.0

In [ ]:
#

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("../Presidents/president_heights.csv")

In [ ]:
data

order                    name  height(cm)
0       1       George Washington         189
1       2              John Adams         170
2       3        Thomas Jefferson         189
3       4           James Madison         163
4       5            James Monroe         183
5       6       John Quincy Adams         171
6       7          Andrew Jackson         185
7       8        Martin Van Buren         168
8       9  William Henry Harrison         173
9      10              John Tyler         183
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
14     15          James Buchanan         183
15     16         Abraham Lincoln         193
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
19     20       James A. Garfield         183
20     21       Chester A. Arthur         183
21     23       Benjamin Harrison         168
22     25        William McKinley         170
23     26      Theodore Roosevelt         178
24     27     William Howard Taft         182
25     28          Woodrow Wilson         180
26     29       Warren G. Harding         183
27     30         Calvin Coolidge         178
28     31          Herbert Hoover         182
29     32   Franklin D. Roosevelt         188
30     33         Harry S. Truman         175
31     34    Dwight D. Eisenhower         179
32     35         John F. Kennedy         183
33     36       Lyndon B. Johnson         193
34     37           Richard Nixon         182
35     38             Gerald Ford         183
36     39            Jimmy Carter         177
37     40           Ronald Reagan         185
38     41       George H. W. Bush         188
39     42            Bill Clinton         188
40     43          George W. Bush         182
41     44            Barack Obama         185

In [ ]:
data.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183